insert into ds.md_ledger_account_s
    select
        chapter,
        chapter_name,
        section_number::int as section_number,
        section_name,
        subsection_name,
        ledger1_account::int as ledger1_account,
        ledger1_account_name,
        ledger_account::int as ledger_account,
        ledger_account_name,
        characteristic,
        is_resident::int as is_resident,
        is_reserve::int as is_reserve,
        is_reserved::int as is_reserved,
        is_loan::int as is_loan,
        is_reserved_assets::int as is_reserved_assets,
        is_overdue::int as is_overdue,
        is_interest::int as is_interest,
        pair_account,
        start_date::date as start_date,
        end_date::date as end_date,
        is_rub_only::int as is_rub_only,
        min_term,
        min_term_measure,
        max_term,
        max_term_measure,
        ledger_acc_full_name_translit,
        is_revaluation,
        is_correct

    from ds.md_ledger_account_s_tmp
on conflict (ledger_account, start_date) do update
    set
        chapter = excluded.chapter,
        chapter_name = excluded.chapter_name,
        section_number = excluded.section_number,
        section_name = excluded.section_name,
        subsection_name = excluded.subsection_name,
        ledger1_account = excluded.ledger1_account,
        ledger1_account_name = excluded.ledger1_account_name,
        ledger_account_name = excluded.ledger_account_name,
        characteristic = excluded.characteristic,
        is_resident = excluded.is_resident,
        is_reserve = excluded.is_reserve,
        is_reserved = excluded.is_reserved,
        is_loan = excluded.is_loan,
        is_reserved_assets = excluded.is_reserved_assets,
        is_overdue = excluded.is_overdue,
        is_interest = excluded.is_interest,
        pair_account = excluded.pair_account,
        end_date = excluded.end_date,
        is_rub_only = excluded.is_rub_only,
        min_term = excluded.min_term,
        min_term_measure = excluded.min_term_measure,
        max_term = excluded.max_term,
        max_term_measure = excluded.max_term_measure,
        ledger_acc_full_name_translit = excluded.ledger_acc_full_name_translit,
        is_revaluation = excluded.is_revaluation,
        is_correct = excluded.is_correct
;
